var urls = [
    '',
    '/billing-history/',
    '/captured-leads-report/',
    '/contact/',
    '/coupons/',
    '/dashboard/',
    '/dashboard/attending/',
    '/dashboard/courses/',
    '/dashboard/events/',
    '/dashboard/groups/',
    '/dashboard/talks/',
    '/engagement-report/',
    '/full-leads-report/',
    '/highlights/',
    '/overview/',
    '/overview/',
    '/payout/',
    '/plataforma-para-webinars-eventials/',
    '/plataforma-webinars-e-transmissoes-online/',
    '/precos-e-planos-webinars/',
    '/revenue-report/',
    '/settings-account/',
    '/settings-casting-password/',
    '/settings-integrations/',
    '/settings-password-change/',
    '/settings-payment-method/',
    '/settings-plan/',
    '/settings/',
    '/software/',
    '/subscription-report/',
    '/surveys/',
    '/talk-create/',
    '/traffic-sources-report/',
    '/transaction-history/',
    '/views-per-talk-report/',
];

urls.push('/pop/'); // dynamics urls
urls.push('/logout/'); // last one!

module.exports = urls;
